server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    preferIpAdress: true

  client:
    registerwithEureka: false
    fetchRegistry: false
